config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :users, only: [:index, :show]
  resources :events do
    member do
      patch :cancel
      patch :remove
      patch :accept
      patch :maybe
      patch :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include AASM

  ACTIVE_STATES = %w[accepted ignored tentative].freeze

  has_many :events_users, inverse_of: :event
  has_many :users, through: :events_users
  has_many :participants, -> { participant }, class_name: 'EventsUser', inverse_of: :event
  has_many :guests, -> { guest }, class_name: 'EventsUser', inverse_of: :event

  has_many :participants_users, through: :participants, source: :user
  has_many :guests_users, through: :guests, source: :user
  
  has_one :user_creator, -> { creator }, class_name: 'EventsUser', inverse_of: :event
  has_one :creator, through: :user_creator, source: :user

  validates :name, presence: true, length: { in: 1..30 }
  validates :description, length: { maximum: 500 }
  validates :location, length: { maximum: 100 }
  validates :date, :start_event, :end_event, presence: true
  validate :start_end_times

  scope :active_events, -> { joins(:events_users).where('events_users.state': ACTIVE_STATES).uniq }

  aasm column: 'state' do
    state :active, initial: true
    state :canceled

    event :cancel do
      transitions from: :active, to: :canceled
    end
  end

  private

  def start_end_times
    errors.add(:end_event, 'must be after start time') if end_event < start_event
  end
end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  include AASM

  belongs_to :event, inverse_of: :events_users
  belongs_to :user, inverse_of: :events_users

  enum user_role: [:creator, :participant, :guest]

  aasm column: 'state' do
    state :ignored, initial: true
    state :accepted, :tentative, :declined

    event :accept do
      transitions from: [:ignored, :tentative], to: :accepted
    end

    event :maybe do
      transitions from: :ignored, to: :tentative
    end

    event :decline do
      transitions from: [:ignored, :tentative, :accepted], to: :declined
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events_users, inverse_of: :event
  has_many :events, through: :events_users

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :name, :surname, length: { maximum: 100 }, format: { with: /\A[a-zA-Z]+\z/ }, on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname])
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :load_event, except: [:index, :new, :create]
  before_action :load_events_user, only: [:show, :cancel, :remove, :accept, :maybe, :decline]

  def index
    @events = current_user.events.active_events.sort_by(&:start_event)
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)
    if @event.save
      EventsUser.create(event: @event, user: current_user, user_role: 0, state: 'accepted')
      flash[:notice] = 'Event was successfully created'
      send_email_to_invited_users('invitation_to_event', @event)
      redirect_to root_path
    else
      flash[:alert] = 'Event was not created'
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      flash[:notice] = 'Event was successfully updated'
      redirect_to root_path
    else
      flash[:alert] = 'Event was not updated'
      render 'edit'
    end
  end

  def cancel
    @event.cancel!
    @events_user.decline!
    flash[:notice] = 'Event was canceled'
    send_email_to_invited_users('cancel_event', @event)
    redirect_to root_path
  end

  def remove
    @events_user.decline!
    redirect_to root_path
  end

  EventsUser.aasm.events.map(&:name).each do |response|
    define_method(response) do
      @events_user.send("#{response}!")
      flash[:notice] = "You #{response} this event"
      EventMailer.user_response(current_user, @event, response.to_s).deliver_later
      redirect_to action: :show
    end
  end

  private

  def load_event
    @event = Event.find_by(id: params[:id]) || not_found
  end

  def load_events_user
    @events_user = @event.events_users.find_by(user: current_user) || not_found
  end

  def send_email_to_invited_users(mailer_method, event)
    invited_users = event.participants_users + event.guests_users
    invited_users.each do |invited_user|
      EventMailer.send(mailer_method, invited_user, event).deliver_later
    end
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :start_event, :end_event, participants_user_ids: [], guests_user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
  def event_badge(event)
    events_user = event.events_users.find_by(user: current_user)
    if event.creator == current_user
      content_tag(:span, 'c', class: 'badge badge-primary')
    elsif events_user.accepted?
      content_tag(:span, 'a', class: 'badge badge-success')
    elsif events_user.tentative?
      content_tag(:span, 'm', class: 'badge badge-secondary')
    else
      content_tag(:span, 'n', class: 'badge badge-danger')
    end
  end

  def events_user_state(event, user)
    event.events_users.find_by(user: user).state
  end
end

app/views/events/_form.haml
= simple_form_for event do |f|
  = f.input :name
  = f.input :description
  = f.input :location
  = f.input :date, as: :date
  = f.input :start_event, as: :time, label: 'Start time'
  = f.input :end_event, as: :time, label: 'End time'
  %hr
  = f.association :participants_users, collection: User.all, include_blank: true,
    input_html: { class: 'chosen-select', 'data-placeholder': 'Select required users' }
  = f.association :guests_users, collection: User.all, include_blank: true,
    input_html: { class: 'chosen-select', 'data-placeholder': 'Select guests' }
  %hr
  = f.button :submit, class: 'btn btn-outline-success'

app/views/events/edit.haml
.col-md-5.mx-auto
  %h3 Editing Event
  = render 'form', event: @event
  = link_to '<< Back', :back, class: 'btn btn-light mt-2'

app/views/events/index.haml
%h3.text-center Calendar
= link_to 'New event', new_event_path, class: 'btn btn-outline-success mb-2'
= month_calendar events: @events, attribute: :date do |date, events|
  = date.strftime('%d')
  - events.each do |event|
    %div{style: ('text-decoration: line-through' if event.canceled?)}
      = event_badge(event)
      = link_to event do
        %small= event.start_event.strftime('%R')
        %b= event.name
%span.badge.badge-primary c
%span - you created this event
%br
%span.badge.badge-success a
%span - you accepted this event
%br
%span.badge.badge-secondary m
%span - maybe you will be on this event
%br
%span.badge.badge-danger n
%span - new event

app/views/events/new.haml
.col-md-5.mx-auto
  %h3.text-center New Event
  = render 'form', event: @event
  = link_to '<< Back', :back, class: 'btn btn-light mt-2'

app/views/events/show.haml
.col-md-8.mx-auto
  %h3.text-center= @event.name
  %table.table.table-hover
    %tbody
      %tr
        %td.text-right.text-secondary date:
        %td= @event.date
      %tr
        %td.text-right.text-secondary start time:
        %td= @event.start_event.strftime('%R')
      %tr
        %td.text-right.text-secondary end time:
        %td= @event.end_event.strftime('%R')
      %tr
        %td.text-right.text-secondary description:
        %td= @event.description
      %tr
        %td.text-right.text-secondary location:
        %td= @event.location
      %tr
        %td.text-right.text-secondary organizer:
        %td
          = link_to @event.creator.name, user_path(@event.creator)
      %tr
        %td.text-right.text-secondary participants:
        %td
          - @event.participants_users.each do |participant|
            = link_to participant.name, user_path(participant)
            - if @event.creator == current_user
              %span (#{events_user_state(@event, participant)})
            %br
      %tr
        %td.text-right.text-secondary guests:
        %td
          - @event.guests_users.each do |guest|
            = link_to guest.name, user_path(guest)
            - if @event.creator == current_user
              %span (#{events_user_state(@event, guest)})
            %br
  - if @event.canceled?
    %p.text-danger Event was canceled. You can remove it from your calendar:
    = link_to 'Remove', remove_event_path(@event), method: :patch, class: 'btn btn-outline-danger'
  - else
    - if @event.creator == current_user
      = link_to 'Edit', edit_event_path(@event), class: 'btn btn-outline-success'
      = link_to 'Cancel', cancel_event_path(@event), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'
    - elsif @events_user.ignored? || @events_user.tentative?
      = link_to 'Accept', accept_event_path(@event), method: :patch, class: 'btn btn-sm btn-outline-success'
      - unless @events_user.tentative?
        = link_to 'Maybe', maybe_event_path(@event), method: :patch, class: 'btn btn-sm btn-outline-info'
      = link_to 'Decline', decline_event_path(@event), method: :patch, class: 'btn btn-sm btn-outline-danger'
  %br
  = link_to '<< Back', :back, class: 'btn btn-light mt-2'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %title Calendar
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-light.bg-light.navbar-expand-lg
      .container
        %ul.navbar-nav
          %li.nav-item= link_to 'Calendar', root_path, class: 'nav-link'
          %li.nav-item= link_to 'Users', users_path, class: 'nav-link'
        %ul.navbar-nav.ml-auto
          - if user_signed_in?
            %li.nav-item.nav-link.active Logged in as #{current_user.email}
            %li.nav-item= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link'
            %li.nav-item= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            %li.nav-item= link_to 'Sign up', new_user_registration_path, class: 'nav-link'
            %li.nav-item= link_to 'Log in', new_user_session_path, class: 'nav-link'
    .container.mt-2
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type == 'notice' ? 'success' : 'info'}"}
          %button.close{'data-dismiss': 'alert', type: 'button'} ×
          #{message}
      = yield

app/views/users/index.haml
%h3.text-center All users
.row
  - @users.each do |user|
    .col-md-3
      .card.mt-3
        = image_tag 'profile_icon.png', class: 'card-img-top mx-auto mt-2', style: 'width: 50%'
        .card-body
          %p= user.email
          = link_to 'Show more >>', user_path(user)

app/views/users/show.haml
%h3.text-center User
.row.mt-3
  .col-md-4
    = image_tag 'profile_icon.png', class: 'img-fluid'
  .col-md-8
    %b= @user.name
    %b= @user.surname
    %hr
    %p= @user.email
= link_to '<< Back', :back, class: 'btn btn-light mt-2'